"""Source metadata (index -> url, title, authors, year, summary) for research_out.json.
Authors/years only where seen in the fetched pages; otherwise None."""
S = {
1: ("https://arxiv.org/html/2608.21962v1", "NoTB: Oracle-Free Triage of LLM-Generated RTL via Cross-Model Formal Consensus", ["Elisavet Lydia Alvanaki","Je Yang","Biruk Seyoum","Luca P. Carloni"], 2026,
    "Closest cross-family formal-consensus system (RTL, MLCAD 2026, arXiv v1): 4 LLM families, SEC clustering; spec-level precision 63/85.3/87/94.7% at >=1..4 families, coverage 100/49/33/27%; judge baseline only at completion level; no AUROC, no complexity analysis; port-name heuristics."),
2: ("https://arxiv.org/html/2607.10139", "LLMs as a Jury: Cross-Model Consensus Can Outperform Process Reward Models for LLM Reasoning", ["Ning Liu"], 2026,
    "States the scatter premise verbatim and gives a closed-form law with latent difficulty and a scalar per-benchmark shared-attractor rate s; shared-error floor ~0 on math, non-trivial on science; recommends 3-4 cross-family models; decorrelation beats more samples (arXiv v3)."),
3: ("https://arxiv.org/html/2609.11085", "Beyond Solver Verdicts: Generative Reward Models for Autoformalization (GenV)", ["Vikash Singh","Debargha Ganguly","Aman Goel","Ali Torkamani"], 2026,
    "Reference-free score distilled from a Z3-equivalence oracle for NL->FOL/SMT (AUROC 0.961); single-model SC K=5 baseline 0.863; judge wins (0.778 vs 0.679) when labels switch from Z3-reference to panel intent (arXiv v2)."),
4: ("https://arxiv.org/html/2410.20936", "Autoformalize Mathematical Statements by Symbolic Equivalence and Semantic Consistency", ["Zenan Li","Yifan Wu","Zhaoyu Li","Xinming Wei","Xian Zhang","Fan Yang","Xiaoxing Ma"], 2024,
    "NeurIPS 2024: selection among k temperature samples of one model using prover-checked symbolic equivalence; labels by manual check; a selector, not a score."),
5: ("https://arxiv.org/html/2505.20047", "Grammars of Formal Uncertainty (GoFU)", None, None,
    "Single-model multi-sample PCFG uncertainty over SMT-LIB programs; selective verification cuts errors 14-100%; SMT autoformalization hurts FOLIO (-44.5%)."),
6: ("https://arxiv.org/html/2311.01740v2", "SAC3: Reliable Hallucination Detection in Black-Box Language Models via Semantic-aware Cross-check Consistency", ["Jiaxin Zhang","Zhuohang Li","Kamalika Das","Bradley A. Malin","Sricharan Kumar"], 2023,
    "Cross-model + cross-question consistency beats self-consistency for QA hallucination detection (AUROC 99.4/97.0)."),
7: ("https://arxiv.org/abs/2410.10135", "FormalAlign: Automated Alignment Evaluation for Autoformalization", ["Jianqiao Lu","Yingjia Wan","Yinya Huang","Jing Xiong","Zhengying Liu","Zhijiang Guo"], 2024,
    "Trained alignment scorer (dual loss) for Lean autoformalization; GenV reports it at 0.752 AUROC on its expanded split."),
8: ("https://arxiv.org/abs/2604.25031", "Faithful Autoformalization via Roundtrip Verification and Repair", ["Daneshvar Amrollahi","Jerry Lopez","Clark Barrett"], 2026,
    "Gold-free roundtrip equivalence check for many-sorted FOL statutes with two LLMs; failing rules show 1.4-2.5x more NLI drift; occupies the roundtrip lane (arXiv v3)."),
9: ("https://arxiv.org/html/2410.08047v2", "Divide and Translate: Compositional First-Order Logic Translation and Verification for Complex Logical Reasoning (CLOVER)", ["Hyun Ryu","Gyeongman Kim","Hyemin S. Lee","Eunho Yang"], 2024,
    "ICLR 2025 NL->FOL: states that incorrect formulas are less likely to be logically equivalent, but notes consistent last-step mistakes yielding equivalent incorrect formulas; selector."),
10: ("https://arxiv.org/abs/2310.17807", "Clover: Closed-Loop Verifiable Code Generation", ["Chuyue Sun","Ying Sheng","Oded Padon","Clark Barrett"], 2023,
    "Consistency checks among code, docstrings and formal annotations; the other 'Clover' (distinct from CLOVER [9])."),
11: ("https://arxiv.org/html/2606.09449", "Reasoning without Gold Standards: A Proxy-Judge Theory of Autoformalization", ["Lei Xu","Xin Quan","André Freitas"], 2026,
    "Reference-free per-axis property checks for autoformalization; no cross-model consensus or label meta-evaluation found."),
12: ("https://arxiv.org/abs/2601.23166", "Monotonic Reference-Free Refinement for Autoformalization", ["Lan Zhang","Marco Valentino","André Freitas"], 2026,
    "Reference-free refinement from prover + LLM-judge feedback; not a consensus metric."),
13: ("https://arxiv.org/html/2608.05670", "When Does Consensus Mean Correctness? Measuring the Agreement-Accuracy Coupling", ["Rasul Khanbayov","Hasan Kurban"], 2026,
    "Agreement certifies correctness only above a threshold set by error diffuseness (diffuse at level L if leading wrong mass <= (1-P(correct))/L); single-model VLM chart QA; disclaims novelty of the concentration-vs-correctness distinction."),
14: ("https://arxiv.org/html/2506.07962", "Correlated Errors in Large Language Models", ["Elliot Kim","Avi Garg","Kenny Peng","Nikhil Garg"], 2025,
    "ICML 2025: models agree 60% when both err (MCQ); more accurate pairs have more correlated errors; difficulty conditioning explicitly left to future work."),
15: ("https://arxiv.org/html/2609.11428", "Wavering Oracles: Selective Updating and Correlated Failures in LLMs", ["Xiaoshn Nee","Haobo Zhong","Xiaomin Ni"], 2026,
    "Mean error correlation 0.285 reduces 7 models to 2.58 effective independent models (4-option MCQ, 600 items)."),
16: ("https://arxiv.org/abs/2607.08065", "When LLMs Agree, Are They Right? Auditing Self-Consistency and Cross-Model Agreement", ["Kaihua Ding"], 2026,
    "Agreement is a positive but weak predictor (rho 0.20-0.59); confident errors recur across providers."),
17: ("https://arxiv.org/abs/2608.18795", "Decomposing Wrong-Consensus Agreement in LLM Self-Consistency", None, 2026,
    "Wrong-consensus decomposition; coverage phi higher on MCQ than open-domain; 'Agreement is graded evidence, not certification.'"),
18: ("https://arxiv.org/html/2606.20158", "N-Version Programming with Coding Agents", ["Javier Ron","Benoit Baudry","Martin Monperrus"], 2026,
    "Knight-Leveson replication with 48 agent implementations: 429 coincident failures vs 115.36 expected; failures concentrate in hard spec parts."),
19: ("https://arxiv.org/abs/2608.29270", "SHADOWBENCH: Toward Reliable Automatic Evaluation of Semantic Alignment in Autoformalization", None, 2026,
    "Benchmark for automatic semantic-alignment evaluation in autoformalization (arXiv v3; EMNLP 2026 per arXiv comment); no cross-model consensus."),
20: ("https://dspace.mit.edu/server/api/core/bitstreams/1331578f-65c1-4665-a0be-1bc3cdc001d5/content", "An Experimental Evaluation of the Assumption of Independence in Multiversion Programming", ["John C. Knight","Nancy G. Leveson"], 1986,
    "IEEE TSE 12(1): 27 versions, 10^6 tests, 1255 tests with >1 version failing; independence rejected; counts coincident failures, Boolean outputs."),
21: ("https://dl.acm.org/doi/10.1109/TSE.1985.231895", "A Theoretical Basis for the Analysis of Multiversion Software Subject to Coincident Errors", ["Dave E. Eckhardt","Larry D. Lee"], 1985,
    "IEEE TSE 11(12) (abstract only): intensity of coincident errors; varying input difficulty implies dependent failures."),
22: ("https://ntrs.nasa.gov/citations/19900036555", "Conceptual Modeling of Coincident Failures in Multiversion Software", ["Bev Littlewood","Douglas R. Miller"], 1989,
    "IEEE TSE 15(12) (abstract only): forced diversity can decrease simultaneous failure probability."),
23: ("https://www.adelard.com/media/vfngprxq/divchap.pdf", "Software Fault Tolerance by Design Diversity (chapter, Lyu ed.)", ["Peter Bishop"], 1995,
    "Review: dissimilar faults do not guarantee dissimilar failures; degree-of-difficulty theory; binary failure-bias example of negatively correlated failures."),
24: ("https://arxiv.org/abs/2606.02837", "Fixing FOLIO and MALLS: Verified Annotations and an LLM-assisted Framework to Focus Human Relabeling", ["Andrea Brunello","Cristian Curaba","Luca Geatti","Michele Mignani","Angelo Montanari","Nicola Saccomanno"], 2026,
    "Wrong-gold rates: v1 (1 Jun 2026) 39%/36%; v2 (3 Sep 2026) 42.5%/42% for FOLIO/MALLS; cite v2 and note v1."),
25: ("https://arxiv.org/abs/2511.11816", "Do LLMs Really Struggle at NL-FOL Translation? Revealing their Strengths via a Novel Benchmarking Strategy", ["Andrea Brunello","Luca Geatti","Michele Mignani","Angelo Montanari","Nicola Saccomanno"], 2025,
    "AAAI 2026: critiques NL-FOL evaluation protocols; proposes a contamination-aware protocol; forward-citation seed (1 citer)."),
26: ("https://arxiv.org/abs/2606.28013", "The Signal-Coverage Matrix: Stratifying Type and Semantic Errors in Statement Autoformalization", ["Chengxiao Dai","Zhaokun Yan","Zhanhui Lin"], 2026,
    "Lean: two judges disagree 26-37 pp on elab-feedback outputs vs 7 pp vanilla; residual traced to gold errors."),
27: ("https://arxiv.org/abs/2501.08613", "Assessing the Sensitivity and Alignment of FOL Closeness Metrics", ["Ramya Keerthy Thatikonda","Wray Buntine","Ehsan Shareghi"], 2025,
    "Reference-based FOL metrics; BertScore aligns more closely with LLM judgement."),
28: ("https://arxiv.org/html/2410.08437", "Autonomous Evaluation of LLMs for Truth Maintenance and Reasoning Tasks (AutoEval)", ["Rushang Karia","Daniel Bramblett","Daksh Dobhal","Siddharth Srivastava"], 2024,
    "ICLR 2025: LLMs cannot verify logical equivalence beyond toy complexity; >20 operators none exceed 50% truth maintenance. Closest formal evidence for judge degradation (M3)."),
29: ("https://arxiv.org/abs/2606.31002", "Beyond Compilation: Evaluating Faithful Natural-Language-to-Lean Statement Formalization", ["Ke Zhang","Patricio Gallardo Candela","Sudhir Murthy","Yi Xie","Zhi Wang","Maziar Raissi"], 2026,
    "LLM judging agrees with human majority 87/97 but is not an equivalence oracle."),
30: ("https://arxiv.org/abs/2608.15565", "Admission Without Answers: Label-Free Certification and Experience Learning for LLM-Based Optimization Modeling", ["Junbo Jacob Lian","Huiling Chen","Hanzhang Qin","Chung-Piaw Teo"], 2026,
    "Three model families + resampled-instance execution: admission precision 0.927 vs 0.871 host majority vote vs 0.726 execution success."),
31: ("https://arxiv.org/abs/2605.25186", "By Their Fruits You Will Know Them: Comparing Formalizations of Law by the Decisions They Encode", ["Julius Vernie","Matthias Grabmair"], 2026,
    "Different formalizations rarely share leaf nodes; matching correctness left open (C3 context)."),
32: ("https://arxiv.org/html/2601.20055", "VERGE: Formal Refinement and Guidance Engine for Verifiable LLM Reasoning", ["Vikash Singh","Darion Cassel","Nathaniel Weir","Nick Feng","Sam Bayless"], 2026,
    "Multi-sample consensus with one formalizer; cross-model consensus 'supported but not yet evaluated' (scoop-risk signal)."),
33: ("https://arxiv.org/html/2511.09008", "A Neurosymbolic Approach to Natural Language Formalization and Verification (ARc)", None, 2025,
    "NL->SMT over a fixed schema; redundant translation with k LLMs; confidence = share of k translations entailing the candidate (same form as c_score); evaluated on downstream QA soundness, not faithfulness labels."),
34: ("https://arxiv.org/html/2608.05439", "SCP-NL2TL: Selective Conformal Prediction with Semantic Verification for NL to Temporal Logic", ["Yixuan Wang","Licheng Luo","Yu Fu","Kaidi Xu","Yue Dong","Mingyu Cai"], 2026,
    "Closest meta-evaluation design: error-detection AUROC for single-model self-consistency, back-translation, judge and fusion channels by difficulty tier (#atomic propositions); SC AUROC rises with tier."),
35: ("https://arxiv.org/abs/2608.30258", "Stratified Consistency Distillation for Natural Language Formalization", ["Zhichao Hou","Ferhat Erata","Joe Lilien","MohamadAli Torkamani"], 2026,
    "K translations from one frontier LLM clustered by semantic equivalence for pseudo-labelling; selector."),
36: ("https://arxiv.org/html/2305.15541", "Harnessing the Power of Large Language Models for Natural Language to First-Order Logic Translation (LogicLLaMA)", ["Yuan Yang","Siheng Xiong","Ali Payani","Ehsan Shareghi","Faramarz Fekri"], 2023,
    "LE metric uses greedy search for the predicate binding that maximises LE (C3 precedent)."),
37: ("https://arxiv.org/html/2509.22338", "Advancing Natural Language Formalization to First Order Logic with Fine-tuned LLMs", ["Felix Vossel","Till Mossakowski","Björn Gehrke"], 2025,
    "Maps predicates by normalised Levenshtein distance (threshold 0.6) before equivalence checking (C3 precedent)."),
38: ("https://arxiv.org/abs/2204.11454", "Natural Language to Code Translation with Execution (MBR-exec)", ["Freda Shi","Daniel Fried","Marjan Ghazvininejad","Luke Zettlemoyer","Sida I. Wang"], 2022,
    "Execution-semantics MBR selection among samples; selector."),
39: ("https://arxiv.org/abs/2207.10397", "CodeT: Code Generation with Generated Tests", ["Bei Chen","Fengji Zhang","Anh Nguyen","Daoguang Zan","Zeqi Lin","Jian-Guang Lou","Weizhu Chen"], 2022,
    "Dual execution agreement among code samples and generated tests; selector."),
40: ("https://arxiv.org/abs/2203.11171", "Self-Consistency Improves Chain of Thought Reasoning in Language Models", None, 2022,
    "ICLR 2023: unique-correct-answer intuition behind agreement-based selection."),
41: ("https://arxiv.org/abs/2302.09664", "Semantic Uncertainty: Linguistic Invariances for Uncertainty Estimation in Natural Language Generation", ["Lorenz Kuhn","Yarin Gal","Sebastian Farquhar"], 2023,
    "Single-model semantic entropy (meaning-level clustering)."),
42: ("https://www.nature.com/articles/s41586-024-07421-0", "Detecting hallucinations in large language models using semantic entropy", ["Sebastian Farquhar","Jannik Kossen","Lorenz Kuhn","Yarin Gal"], 2024,
    "Nature 2024: semantic entropy detects confabulations; single model."),
43: ("https://arxiv.org/abs/2404.18796", "Replacing Judges with Juries: Evaluating LLM Generations with a Panel of Diverse Models (PoLL)", None, 2024,
    "Judge panel from disjoint families, >7x cheaper than a single large judge."),
44: ("https://aclanthology.org/2023.findings-emnlp.785/", "Error Detection for Text-to-SQL Semantic Parsing", None, 2023,
    "Findings EMNLP 2023: trained parser-independent error detector (semantic-parsing analogue; abstract only)."),
45: ("https://arxiv.org/abs/2403.09732", "PET-SQL: A Prompt-Enhanced Two-Round Refinement of Text-to-SQL with Cross-consistency", None, 2024,
    "Cross-consistency across different LLMs for SQL selection (abstract only)."),
46: ("https://arxiv.org/abs/2203.07814", "Competition-Level Code Generation with AlphaCode", None, 2022,
    "Behavioural clustering/filtering of samples; selector."),
47: ("https://lucykuncheva.co.uk/ensemble_diversity.html", "Measures of diversity in classifier ensembles (Kuncheva & Whitaker 2003) - author page", ["Ludmila I. Kuncheva","Christopher J. Whitaker"], 2003,
    "Classical ensemble diversity measures incl. double fault and coincident failure diversity."),
48: ("https://arxiv.org/abs/2605.29800", "Nine Judges, Two Effective Votes: Correlated Errors Undermine LLM Evaluation Panels", ["Guneet Kohli"], 2026,
    "9 judges ~ 2 independent votes; difficulty explains 6.8% of the Condorcet gap."),
49: ("https://arxiv.org/abs/2601.23045", "The Hot Mess of AI: How Does Misalignment Scale With Model Intelligence and Task Complexity?", ["Alexander Hägele","Aryo Pradipta Gema","Henry Sleight","Ethan Perez","Jascha Sohl-Dickstein"], 2026,
    "Error-incoherence (variance share) rises with reasoning length/task difficulty (within-model) - supports M1 direction."),
50: ("https://arxiv.org/abs/2606.27288", "When Does Combining Language Models Help? A Co-Failure Ceiling on Routing, Voting, and Mixture-of-Agents Across 67 Frontier Models", ["Josef Chen"], 2026,
    "All-wrong rate beta caps ensemble gains; rho cannot identify beta; co-failure depends on answer format."),
51: ("https://arxiv.org/abs/2607.23931", "State-dependent error correlations shape voting thresholds in committees of AI agents", ["Haifeng Li","Mo Hai"], 2026,
    "Shared errors create a positive asymptotic error floor for majority voting; dependence differs between good and bad cases."),
52: ("https://arxiv.org/abs/2603.06612", "Consensus is Not Verification: Why Crowd Wisdom Strategies Fail for LLM Truthfulness", ["Yegor Denisov-Blanch","Joshua Kazdan","Jessica Chudnovsky","Rylan Schaeffer","Sheng Guan","Soji Adeshina","Sanmi Koyejo"], 2026,
    "Aggregation fails as a truth signal where errors are strongly correlated (contradicting evidence for consensus)."),
53: ("https://arxiv.org/abs/2607.20464", "Stochastic Sampling is Epistemically Shallow", ["Izhar Ali"], 2026,
    "Self-consistency lacks cross-question structure; only a diverse ensemble surfaces what a model does not know."),
54: ("https://arxiv.org/html/2606.14113", "Simulating Students' Java Programming Errors with Large Language Models", ["Ali Keramati","Jie Cao","Iman Mohammadi","Mark Warschauer","Yang Shi"], 2026,
    "Harder problems elicited more heterogeneous erroneous outputs (analogy only for M1)."),
55: ("https://arxiv.org/abs/2006.16736", "Beyond accuracy: quantifying trial-by-trial behaviour of CNNs and humans by measuring error consistency", ["Robert Geirhos","Kristof Meding","Felix A. Wichmann"], 2020,
    "NeurIPS 2020 error-consistency (kappa) metric for whether systems err on the same inputs."),
56: ("https://arxiv.org/abs/2605.29001", "FormInv: A Measurement Protocol for Semantic Invariance in Mathematical Reasoning Benchmarks", ["Nishal Thomas","Noel Thomas"], 2026,
    "Cross-model unanimity used to find paraphrase errors."),
57: ("https://arxiv.org/abs/2506.10903", "Beyond Gold Standards: Epistemic Ensemble of LLM Judges for Formal Mathematical Reasoning", ["Lan Zhang","Marco Valentino","Jordan Meadows","Andre Freitas"], 2025,
    "Ensemble of LLM judges for autoformalization evaluation (judge-side, not translation consensus)."),
58: ("https://arxiv.org/abs/2605.13817", "Neurosymbolic Auditing of Natural-Language Software Requirements", ["Bethel Hall","William Eiers"], 2026,
    "Variation across independent formalizations treated as an ambiguity signal (requirements)."),
59: ("https://arxiv.org/abs/2609.03422", "Inferred Generative-Process Diversity Predicts Correlated Failure Across Language Models", ["Ross Tieman","Evan Markou"], 2026,
    "Generative-process diversity associated with reduced correlated failure across 38 models."),
60: ("https://www.inf.pucrs.br/~zorzo/cs/n-versionprogramming.pdf", "N-Version Programming: A Fault-Tolerance Approach to Reliability of Software Operation", ["Liming Chen","Algirdas Avizienis"], 1978,
    "FTCS-8 1978: 'faulty but identical results (due to missing logic) may outvote correct results'; defines inexact voting - the identical-wrong vs coincident-failure distinction for C4."),
61: ("https://arxiv.org/abs/2603.25450", "Cross-Model Disagreement as a Label-Free Correctness Signal", ["Matt Gorbett","Suman Jana"], 2026,
    "Cross-model perplexity as a label-free correctness score (MMLU AUROC 0.75 vs 0.59); not solver-based."),
62: ("https://arxiv.org/abs/2607.19899", "Harnessing Disagreement: Detecting Correlated Agreement Blindness in Multi-Agent Triage", ["Shay Seiya McDonnell","Avantika Singh","Quoc-Viet Pham","Vratislav Havlik","Gregory M.P. O'Hare"], 2026,
    "Stronger base learners increase error correlation and reduce disagreement; 57.2% of errors under agreement (non-LLM)."),
63: ("https://arxiv.org/abs/2608.00285", "Sixteen models, fewer than two voices: measuring ensemble dispersion where no answer is uniquely correct", ["Mario Vega-Barbas","Lidia Mora-Valenciano","Iván Pau","Fernando Seoane","Farhad Abtahi"], 2026,
    "16 models from 10 families give 1.69 distinct formulations vs 1.43 for one model (effective diversity bound, C5)."),
}
