"""Writes the iteration-5 review JSON (.terminal_claude_agent_struct_out.json)."""
import json
E11="gen_art_experiment_11"; E12="gen_art_experiment_12"; E13="gen_art_experiment_13"; E14="gen_art_experiment_14"; EV4="gen_art_evaluation_4"
review = {
"overall_assessment": (
"The iteration-5 headline numbers come from artifacts that ran, and I recomputed them from the raw per-item files (audit/recompute_*.py/.json). "
"E2-A (art_ngTPhaVyXxhh, per_item_E2A.jsonl, R_AB): DT V0 0.9162, p_peer_text 0.9194, local Qwen judge 0.9129; L25 V0 0.4429 (42 rows / 7 CORRECT); ALL strat 0.8904. "
"E2-B (art_REMRsYjY1N4s, per_item_E2B.jsonl): V0 pooled 0.742, flash-lite 0.491. "
"R_COMP FREE (art_5KczEbsFPx25, per_item_rcomp_free.jsonl): within-template c_align 0.8007 vs flash-lite disguised 0.5842 on 1,706 paired rows; c_hyb 0.817; c_nf 0.743. All match the report, so results_reported is true. "
"The record is still not sound. "
"(1) Evaluation 4 (art_TWLKblwXVifE) wrote a complete corrected record (record_final.md, sections 6–17: hypothesis verdicts, prior art, §4.4/§4.5 caveats, the §4.6 rewrite, one cost table, the spend table with $2.313 unaccounted, the extended dead ends, coverage against the request, 'What we have learned'). §5.6 says these corrections 'have been applied inline'. Many were not. §4.6 still says the d_floor 'closely matches … accounts for the observed disagreement' and 'R_exact AUROC (0.683) is the theoretical performance … on R_COMP'; eval 3 and record_final §12 say the reverse. §4.4 still says the drift gates 'all pass'. §3.3 still records the FREE delta +0.214 on labels that dataset 5 invalidated, with no marker. Several struck-and-replaced numbers (§4.2 CIs, COMPOUND e, §3.4 MEANING_RENAME) were changed silently rather than with the ~~original~~ [Correction …] markers record_final supplies. "
"(2) The new §5 section contradicts its own artifacts. It says the flash-lite bar has 'zero scored rows in R_AB' on E2-A. per_item_E2A.jsonl has 71 R_AB rows scored, and on DT V0 − flash-lite is −0.083 [−0.266, 0.137]. It reports E2-B rename FA 1.0/0.968 as 'the rename problem persists'. The paired flips are 0.129/0.167: V0 already flags 0.83 of CORRECT parents (I recomputed 0.833). It labels H-MECH (iii) CONFIRMED with a CI that covers 0. The iteration-5 spend lines are wrong: exp 11 spent $2.045 (not 'included in dataset 4'), exp 12 $0.830 (not $2.05), exp 14 $0.219 (not $0.00). The budget was $12, not $7. "
"(3) The §5 write-up leaves out the unfavourable results its artifacts contain. E2-A long pool: V0 0.603 is below the local judge (0.695), p_peer_text (0.704) and L3 (0.706), and nested [S4+V0]−S4 = −0.064 [−0.134, −0.002]. ALL nested −0.009, so consensus adds nothing on fresh data. R_COMP FREE: aligner-free c_exact 0.606 ≈ judge (Δ +0.018 n.s.), so the advantage is the name aligner. The frontier judge beats c_align there (0.852 vs 0.801). In the original view the advantage over the judge shrinks with length (W1 +0.285 → W3 +0.084; Δ-of-Δ −0.201 [−0.307, −0.083]). The pre-registered placebo bar failed (17/20). The majority-rule FA is 0.691. On development E, V0 flags 81% of CORRECT L25 rows and 91% of word-T3 CORRECT rows (exp 14 T5), and V0 − judge on L25 is +0.072 [−0.015, 0.153], n.s. "
"(4) Earlier-iteration contradictions remain: M3 is 'DISCONFIRMED' in §3.2, §3.6 item 9 and Related Work but 'INCONCLUSIVE' in §3.5, §3.6 item 6 and the limitations. §3.4 ranks operators by consensus AUROC in the same paragraph that calls that column an artefact. §3.3 still shows T2 'PASS True'. "
"(5) Still absent: the research artifact art_VIF75I5R6f0v (no marker, scoop rule or C1–C5), the coverage-against-request table, the function inventory, and §5.1 reasoning (no previous-review score, no iter-4 upd_hypo move 'deepen' / title 'Cross-model agreement, tested on fresh data'). "
"Against the user's request, the run still has no confirmed answer on long, heavily conditioned sentences with free vocabulary. Every fresh-data long-sentence cell is either untestable or unfavourable to consensus, and the summary does not say this plainly. Because statements in §4.6 and §5.2 contradict the run's own files, soundness is 1 and the review is blocking. The fix is almost entirely transcription from record_final.md and the four iteration-5 tables.md files."),
"strengths": [
"Every iteration-5 headline number I recomputed from raw per-item files reproduces exactly: E2-A DT 0.916 / L25 0.443 / ALL 0.890; E2-B V0 0.742 pooled vs flash-lite 0.491; R_COMP FREE c_align 0.801 vs judge 0.584 on 1,706 paired rows. No projected or placeholder number is presented as a result.",
"The iteration-5 section labels testability honestly at the top level. All three confirmation arms are NOT_TESTABLE, R_COMP FREE is PROVISIONAL, E2-B is exploratory under unaudited gold, and the label-coupling diagnostic (V0 0.737 → 0.611 with gold-equivalent peers removed) is reported.",
"Several previous-review MUST-FIX items were fixed. §4.2 CIs now match exp 9's tables.md. COMPOUND e is 0.282/0.107. G2 is NOT_READ. M3 is given under both specifications. CSC is downgraded to 'provisional negative'. §4.3 gives base FA next to recall and corrects the LOCAL2 tie artefact and the judge's 12.4%. §3.4 relabels MEANING_RENAME as an ERROR operator. The k-cost column is per sentence. Placeholder artifact IDs are replaced. E is called development data. §4.1 now has a reasoning block and a spend list.",
"GG and V1–V5 are recorded as failed or not selected, with their gate values and the selection-stability and permutation-null numbers, and GG is added to the dead-ends table.",
"The DT (ProverQA, prover-built gold) cell is correctly identified as the only testable fresh-data cell and is reported with its local-judge comparison (Δ +0.003 n.s.). The report does not claim a win there."
],
"dimension_scores": [
{"dimension": "soundness", "score": 1,
 "justification": "Several statements contradict the run's own files. §4.6 and the iter-4 summary: 'd_floor closely matches … accounts for', and 0.683 called an R_COMP AUROC, where eval 3 and record_final §12 say the opposite. §5.2: 'flash-lite has zero scored rows in R_AB', where the file has 71 and V0 − flash-lite on DT is −0.083. §5.3: rename FA read as a rename effect, where the paired flips are 0.13/0.17. H-MECH(iii) is 'CONFIRMED' with a CI covering 0. M3 is DISCONFIRMED in one place and INCONCLUSIVE in another. §5.6 says corrections were applied when many were not. By the rule, soundness is 1.",
 "improvements": [
  "Replace §4.6 with record_final.md §12 verbatim, and remove the 'closely matches' and '0.683 theoretical AUROC' sentences from §4.6 and §4.7 item 7.",
  "Correct §5.2 to 'flash-lite scored on 71 R_AB rows (63 DT, 8 long); DT V0 − flash-lite −0.083 [−0.266, 0.137] n.s.; long pool not testable' (source exp 11 tables.md, DT cell).",
  "Replace every rename-FA claim on fresh data with FA, base FA and paired flip side by side (E2-A rename_E2.json; E2-B analysis_E2B.json::rename).",
  "Make M3 read INCONCLUSIVE everywhere (§3.2 verdict table and heading, §3.6 item 9, Related Work), with a [Correction] marker."]},
{"dimension": "presentation", "score": 2,
 "justification": "The chronology holds and each iteration section exists. But corrections are a mix of marked in place (C1–C8) and silently replaced (§4.2 CIs, COMPOUND, §3.4), and §5.6's blanket 'applied inline' statement is false for about half of record_final's sections. Iteration-5 spend and budget figures are wrong, and §5.1 records no reasoning.",
 "improvements": [
  "Use record_final.md's '~~original~~ [Correction, iter 4: …; source …]' markers for every changed number in §3–§4.",
  "Add a §5.1 reasoning block: previous review score 3 / blocking / 11 critiques; iter-4 upd_hypo move 'deepen', title 'Cross-model agreement, tested on fresh data', move_rationale; what each of the five artifacts was meant to settle.",
  "Replace the iteration-5 spend line with the ledgers: exp 11 $2.045 (cost_E2A.json), exp 12 $0.830 (cost_ledger_master.jsonl), exp 13 $1.97, exp 14 $0.219 (cost_ledger.jsonl), eval 4 $0. Say the run-level budget was $12 and name the stop times (11:39–11:40 UTC)."]},
{"dimension": "contribution", "score": 2,
 "justification": "Every executed artifact has a section. But the iteration-5 sections carry about a quarter of their artifacts' tables, and the omitted part is mostly the unfavourable evidence. E2-A long pool, L25, nesting and flash-lite-on-DT tables are missing. So are R_COMP FREE c_exact, frontier, orig-view complexity, operating point, placebo and H-MECH(i); exp 14 T5 e/d by stratum, T5b/T5c, T8 L25 and GG_B bracket; eval 4's coverage, dead-ends, prior-art and cost sections. The research artifact still has no section.",
 "improvements": [
  "Transcribe exp 11 tables.md cells R_AB LONG, L25, EXC, ALL (paired Δ and nested rows), H-MECH, H-RENAME by stratum, complexity, placebo, cost.",
  "Transcribe exp 13 tables.md: per-metric table incl. c_exact, secondary deltas, operating points, complexity, H-MECH (i)–(iv), frontier, audit-labelled view, noise-correction validity + differential check, placebos.",
  "Transcribe record_final.md §6, §7, §13–§17 as new or replacement sections."]}
],
"critiques": [
{"category": "evidence", "severity": "major",
 "description": "§5.6 says eval 4's corrections 'have been applied inline throughout'. Many of the record_final.md sections that eval 4 (art_TWLKblwXVifE) wrote for transcription were never carried into the report, and earlier text they correct is still there. Not applied: §12 (§4.6 rewrite). The report still says 'predicted d_floor (0.402) closely matches the observed END_MAJ d (0.415), indicating that the Part-1 model accounts for the observed disagreement' and 'R_exact AUROC (0.683) is the theoretical performance … on R_COMP'. §4.7 item 7 repeats 'closely matches', and the calibration failure is still blamed on non-transitivity. The 77%/61% wrong-peer decomposition, which record_final calls the main mechanism finding, is absent. §11 (§4.4/§4.5 caveats): §4.4 still says the drift gates 'all pass', with no stop-rule UNDECIDED and no 0.12-vs-0.84 track-H signal. §4.5 still says '70.7% contaminated' without 'upper bound'. §3.3 still gives FREE Δ +0.214 with no void marker. Also not transcribed: §6 (hypothesis verdicts), §7 (prior art, art_VIF75I5R6f0v), §13 (one cost table), §14 (spend table incl. $2.313 unaccounted), §15 (dead ends: the c_nf row still cites 'SWAP recall 0.512', and rename-selection, B1, FOL-Triage rewrite-FA, P2/P4, CSC variants and E2 EXC-core are missing), §16 (coverage against the request) and §17 ('What we have learned' replacement). §2.3 still says '588 items' (eval 1 common sets are regime-specific, e.g. R_SOLVER_CONS n = 373). eval 4's own reviewer_checklist.csv marks 9/11 items CLOSED because record_final.md contains them; the report does not. This is the third iteration in which a finished correction existed on disk and was not carried over.",
 "suggested_action": "Transcribe record_final.md §6, §7, §11, §12, §13, §14, §15, §16 and §17 into the report, each at its anchor, with its ~~original~~ [Correction …; source …] markers. Delete §5.6's 'applied inline throughout' and list which record_final sections were applied. Fix §2.3's '588' from eval 1 (common-set n per regime). This is transcription only."},
{"category": "rigor", "severity": "major",
 "description": "§5.2 (E2-A, art_ngTPhaVyXxhh) contradicts its artifact and leaves out every unfavourable cell. (a) 'The pre-registered flash-lite disguised bar has zero scored rows in R_AB'. I recomputed from per_item_E2A.jsonl: 1,427 rows have a flash-lite score, 71 of them in R_AB (63 DT, 8 long). tables.md DT cell: V0 − judge_cheap_disg = −0.083 [−0.266, 0.137] (n = 63), and ALL −0.082. Consensus sits below the pre-registered bar on the only cell where both exist. (b) Long pool (L25+EXC, 94 rows): V0 0.603 < local judge 0.695 < p_peer_text 0.704 ≈ l3_z3 0.706. V0 − local judge −0.091 [−0.219, 0.017]. Nested [S4_E2+V0] − S4_E2 = −0.064 [−0.134, −0.002]: adding consensus hurts. (c) ALL: [S4+V0]−S4 −0.009 [−0.034, 0.014]; c_score_align − S4 −0.040. On fresh data consensus adds nothing over the local stack. The artifact summary says this ('consensus ties a local 8B judge and adds nothing over it'); the report does not. (d) L25: c_score_align − p_peer_text −0.231 [−0.500, −0.064]. (e) H-MECH (iii) is printed as 'CONFIRMED … CI includes 0' ([−0.036, 0.855]), which contradicts itself. (f) Omitted: pilot metrics on E2 (joint-conflict 0.500, arity 0.507, dangling 0.413 inverted, rerun-Jaccard 0.713); R_A/R_VEX/nopilot cells; rename flips by stratum (NONCE L25 0.18, EXC 0.28, DT 0.93; SYN L25 0.0), so the rename weakness is concentrated in DT; drift gate PASS 0.955 on 269 items; deviations (17); cost ($0.000938/sentence FULL, 1.46 CPU-s marginal); spend $2.045, not 'included in dataset 4'. (g) E2-A is described as 'the untouched 110-sentence subset'. In fact all 550 sentences / 5,500 candidates were generated and scored; the 110 are the panel-labelled sha1 prefix.",
 "suggested_action": "Rewrite §5.2 from exp 11 tables.md: the T1 verdict block verbatim; R_AB LONG, L25, EXC, DT and ALL metric tables with paired-Δ rows (source results/auroc_cells.json); H-MECH with (iii) reworded as 'direction consistent, n.s.'; H-RENAME with FA / base FA / flip by stratum; the pilot-metric rows; cost and spend. Replace 'zero scored rows in R_AB' with the 71-row count and the DT/ALL V0 − flash-lite deltas. Add a one-line reading: on fresh data consensus ties the local judge on DT, is below it on the long pool, and adds nothing to the S4 stack."},
{"category": "evidence", "severity": "major",
 "description": "§5.4 (R_COMP FREE, art_5KczEbsFPx25) reports the favourable provisional delta and leaves out the tables that qualify it. (a) Aligner-free c_exact within-template AUROC is 0.606 (recomputed 0.6057). c_exact − judge_disg = +0.018 [−0.025, 0.059] n.s., and c_exact − judge_orig = −0.029 n.s. Without the name-similarity aligner, consensus does no better than the cheap judge in the in-scope free-vocabulary regime. The MAPPED label comes from a vocabulary-map search, so this is the shared-instrument concern again, and the report never states it. (b) The frontier judge (gemini-3.1-pro, 150 rows) reaches 0.852 vs c_align 0.801 (Δ −0.051 [−0.153, 0.044]), and [c+frontier]−[c] = +0.086 [0.003, 0.166]. (c) Complexity, which the user ranks first: in the original view the c_align − judge gap shrinks with length (W1 +0.285, W2 +0.164, W3 +0.084; Δ-of-Δ −0.201 [−0.307, −0.083]). c_align's own slope W3−W1 is −0.133 [−0.223, −0.035] in the disguised view. (d) The pre-registered placebo bar FAILED (17/20 shuffles cover 0, bar 18), and H-MECH (i) failed its bar (non-agreeing peers of MAPPED are 0.295/0.407 ERROR). (e) The majority-rule operating point flags 0.691 of MAPPED rows (recomputed 0.691). (f) The report presents 'noise-corrected c_align 0.973 vs judge 0.632' without saying that the artifact's differential check shows contamination is differential (audited-faithful ERROR_CERT rows score 0.74), which invalidates the correction. The orig-view Δ +0.171 and the audit-labelled view (c_align 0.899 vs judge_disg 0.522; vs judge_orig only +0.105 [0.011, 0.215]) are also omitted.",
 "suggested_action": "Add to §5.4, from results/tables.md with source lines: the full per-metric table including c_exact, g_align, g_nf and judge_local; the secondary deltas; the frontier block; the complexity table (both views); operating points; H-MECH (i)–(iv); placebos with FAIL stated; the audit-labelled view; the noise-correction table with its validity flags and the differential check. Add one sentence: 'the provisional advantage is carried by the aligner (c_exact ≈ judge), is beaten by the frontier judge, and shrinks with length in the original view'."},
{"category": "rigor", "severity": "major",
 "description": "§5.3 (E2-B, art_REMRsYjY1N4s) repeats the rename misreading that the previous review corrected for §4.3, and misstates spend and scope. (a) 'RENAME_NONCE FA 1.0; RENAME_SYN FA 0.968. The rename problem persists'. analysis_E2B.json::rename gives base FA on the CORRECT parents of 0.833/0.839 and paired flips of only 0.167/0.129. The any-label controls give flips 0.107/0.088 with reverse flips 0. I recomputed V0 FA on CORRECT rows at 0.833, and V0 flags 0.913 of all E2-B candidates. Most of the 'rename FA' is base FA; the finding is that V0 flags nearly everything on long sentences. (b) Spend is $0.830 (cost_ledger_master.jsonl), not $2.05. (c) 'unaudited MALLS gold, which iteration 3 showed is itself 42% wrong'. 42% is Brunello et al. [3]; the run's own figure is that E's panel rejected 82% of MALLS gold (dataset E card). (d) 'H_MECH(iii) REFUTED' is Δ −0.225 [−0.537, 0.113], CI covering 0. H-MECH (i)/(ii) are UNINFORMATIVE by construction (tautological under gold-equivalence labels); the report does not say so. (e) Omitted: the V0_decoupled − flash-lite lead +0.133 [−0.024, 0.314] (CI covers 0, so the exploratory advantage does not survive label decoupling); nested [S4+V0]−S4 +0.120; that S4_E2B dropped every local judge and round trip (no GPU), so S4 at 0.498 is not the stack used elsewhere; system τ V0 0.467 vs flash-lite −0.315; the V1–V5 rows; the frontier run (10 rows only).",
 "suggested_action": "Rewrite §5.3 from analysis/tables.md §0–§6: the full exploratory table with tie rates, the delta table, the label-coupling line with its CI, H-MECH with the UNINFORMATIVE labels, the rename block with base FA and paired flips, the S4 feature substitutions, system τ, and the correct spend. Replace 'rename problem persists' with 'V0 flags 83% of CORRECT parents; renaming adds 13–17% flips'."},
{"category": "evidence", "severity": "major",
 "description": "§5.5 (exp 14, art_EU1yuNrRl4od) and 'What we have learned' omit the development-data facts that bear most directly on long sentences. (a) T5: V0 at c > 0.5 has d = 0.811 on L25 and 0.913 in word tercile T3. It flags 81–91% of CORRECT long translations, with an overall flag rate of 0.740. (b) T8: V0 − judge_cheap_disg on L25 is +0.072 [−0.015, 0.153], n.s. The 'beats the best cheap judge by +0.101' headline is ALL-strat. On the stratum the user cares about most, the development advantage is not significant; record_final §16 already gives L25 Δ +0.069 [−0.020, 0.148]. (c) c_exact beats V0 on CTRL (+0.119 [0.028, 0.208]). (d) The V1/V3/V5 mechanism, where plurality normalisation trades d for e (ALL d 0.490 → 0.174, e 0.140 → 0.343; MEANING_RENAME-type e 0.502 → 0.872), is the iteration's answer to the 'wrong-peer cause' the hypothesis set out to attack, and it is not in the report. T5b shows no variant lowers d without raising e. (e) GG gates g1 and g2 'pass' only because base FA is 0.83 (T10); this is not stated. GG_B is called 'UNTESTED' although its all-accepted bracket was computed (ALL-strat 0.653, e 0.334, Δ vs V0 −0.090). G-B is NOT_TESTABLE (53 YES pairs). (f) Spend is $0.219 (cost_ledger.jsonl), not '$0.00 (CPU-only)'. (g) The 'NET +0.401' in 'What we have learned' is exp 14 T5c's V0 row but carries no source; §3.5 gives NET +0.356 (END_MAJ), and the two are not reconciled.",
 "suggested_action": "Add exp 14 T5, T5b, T5c, T8 (with the L25 column), T10 with its base-FA caveat, T11 and T13 to §5.5 with source lines. State in 'What we have learned' that the development advantage on L25 is +0.072 [−0.015, 0.153] n.s. and that V0 flags 81% of correct L25 translations. Name the NET definition next to each NET value."},
{"category": "scope", "severity": "major",
 "description": "Coverage against the original request is partial, and the report still has no table saying so. It was a MUST-FIX last round, and record_final §16 has one ready. On the user's top priority, long heavily conditioned sentences with no controlled vocabulary, the evidence now is as follows. Development E L25: n.s. vs judge. E2-A long pool: V0 below the local judge and hurting the S4 stack. E2-A L25: 0.443 on 7 CORRECT rows. E2-B: untestable, unaudited gold, lead not surviving decoupling. R_COMP FREE: provisional only, aligner-carried, advantage shrinking with length in the orig view. Error-type identification is negative outside a shared vocabulary. Invariance: V0 fails rename controls. The deliverable functions exist (exp 11 lib/nl2fol_metrics.py with 'measures / does not measure' docstrings; exp 14 lib/api.py; freelab, consensus_lib) but no section lists them. 'What we have learned' still opens with 'the strongest gold-free faithfulness signal found' and with SIG 0.954, and it never states that no long-sentence cell on fresh data favours consensus.",
 "suggested_action": "Transcribe record_final §16 as 'Coverage against the request' and fill its 'pending in iteration 5' column from confirm_verdict_E2A.json, analysis_E2B.json, confirm_verdict_rcomp.json and exp 14 selection.json, with one-line answers per requirement. Add a function-inventory table (function, file, input signature, what it measures / does not measure, gold-free or gold-using) from exp 11 lib/nl2fol_metrics.py, exp 14 lib/api.py and lib/PROVENANCE.json. Rewrite the first paragraph of 'What we have learned' so the long-sentence verdict is stated first."},
{"category": "rigor", "severity": "major",
 "description": "Internal contradictions left from earlier iterations. (a) M3 is 'DISCONFIRMED' in the §3.2 verdict table, in the §3.2 heading 'M3: complexity slope (DISCONFIRMED)', in §3.6 item 9 ('M3 disconfirmation is informative … cannot be relied upon') and in Related Work ('our M3 disconfirmation'). It is 'INCONCLUSIVE (two specifications conflict)' in §3.5, §3.6 item 6, §5.6 and the limitations. (b) §3.4 says 'c_align … most sensitive to SWAP (0.882) and NEG (0.869), least sensitive to DROP' and then, in the same paragraph, that the per-operator consensus column is a base-endorsement artefact from which no ranking can be read. (c) §3.3 still shows the SIG row as 'PASS True' and 'the largest effect observed in any test', with no marker that SIG is out of scope; §3.6 item 3 says NOT CONFIRMED. (d) The §3.3 cost line gives the frontier judge as '$0.00605 per call (30.2× …)', but 30.2× is $0.00365/item ÷ $0.000121, and exp 13 now gives $0.00477/call. (e) The CSC summary still says 'below … the flash-lite judge (0.664)'. The paired Δ is −0.050 [−0.212, +0.107], n.s. (exp 9 T5), and this is not stated.",
 "suggested_action": "Put [Correction] markers on each of (a)–(e): M3 → INCONCLUSIVE in all four places; strike the §3.4 operator ranking sentence; strike 'PASS True' / 'largest effect' in §3.3 or annotate 'out-of-scope SIG'; use the record_final §13 cost table; add 'n.s.' to the CSC-vs-flash-lite sentences in §4.2 and §4.7."},
{"category": "novelty", "severity": "major",
 "description": "The run's positive claims still have no nearest-neighbour check in the record, and the research artifact art_VIF75I5R6f0v still has no [ARTIFACT] marker, no scoop-rule statement and no C1–C5 verdict table. This was MUST-FIX last round, and record_final §7 contains the section ready to paste. The references [19]–[22] appear only in Related Work prose. The iteration-5 positive claims are the R_COMP FREE provisional c_align > judge, the DT 0.916 cell and 'V0 stands'. Their nearest neighbours: ARc/Bayless et al. 2025 (arXiv 2511.09008) uses the same score form (share of k translations entailing the candidate) over a fixed shared schema. GenV (arXiv 2609.11085) reports single-verifier AUROC 0.961 on z3-reference labels. In the run's own R_COMP FREE data the frontier judge beats c_align. What this run adds beyond ARc is a per-candidate meta-evaluation against judges on NL→FOL with free vocabulary, and the fresh-data version of that is untestable or negative. The report should say that.",
 "suggested_action": "Paste record_final §7 as '3.7 Prior-art positioning [ARTIFACT:art_VIF75I5R6f0v]' (scoop rule, closest-neighbour table, C1–C5 verdicts with qualifiers). Under §5.4 and in 'What we have learned', add one sentence each naming ARc and GenV and stating what the provisional FREE result adds (and that the frontier judge exceeds it there)."},
{"category": "clarity", "severity": "major",
 "description": "§5.1 records what iteration 5 attempted but not why. It omits the previous review (score 3, blocking, 11 critiques) and which critiques eval 4 was built to close. It omits the iter-4 hypothesis update: move 'deepen', title 'Cross-model agreement, tested on fresh data', relation 'evolution', confidence 'decreased', and the move_rationale 'confirm frozen consensus on untouched E2/R_COMP FREE (fix each once), attack wrong-peer cause at $0; CSC closed'. It omits why V1–V5 were the chosen attack on the wrong-peer cause, and the pre-registered stopping rules. The budget story is also inconsistent. §5.7 says 'the run-wide budget ($7.00)'. The iteration-5 artifacts all state a $12 run-level budget exhausted at about 11:39–11:40 UTC. The listed spend is wrong for three of five artifacts (exp 11 $2.045, exp 12 $0.830, exp 14 $0.219; actual iteration total about $5.06). The $2.313 unaccounted from iteration 4 (record_final §14) is not mentioned.",
 "suggested_action": "Open §5 with an 8–10 line reasoning block drawn from iter_4/upd_hypo (.terminal_claude_agent_struct_out.json: title, move, move_rationale, coverage_statement) and iter_5/gen_strat/gen_strat_1/README.md. Replace the spend line with a ledger-sourced table (per artifact; budget $12; stop time). Carry record_final §14's unaccounted $2.313 into §4."},
{"category": "evidence", "severity": "minor",
 "description": "The dead-ends table in §5.7 adds GG but is otherwise unchanged. The c_nf reason is still 'SWAP recall 0.512', while §3.4 now says the name-free line ended through MEANING_RENAME blindness plus the failed pre-registered selection, with a 'see below' that points to nothing. Missing rows are listed in record_final §15. Iteration 5 adds candidates too: V1/V3/V5 plurality normalisation (trades d for e; selection NONE), GG_B (bridges absorb ADD/DROP errors, bracket 0.653), the gloss-gated R_COMP FREE labelling route (gate failed twice: haiku 0.776/0.561, qwen 0.855/0.883), and the E2/E2-B panel route (budget-stopped, 0 completed E2-B batches).",
 "suggested_action": "Replace the table with record_final §15 plus these iteration-5 rows, each with a source file (exp 14 selection_E.json / ggb_dev.json; exp 13 gate_diagnostics.json; exp 12 e2b/progress.jsonl)."},
{"category": "methodology", "severity": "minor",
 "description": "The iteration-5 summary headlines cells too thin to support what is said about them. 'L25 on E2 is near chance … the consensus metric collapses on the long-sentence confirmation stratum that matters most' rests on 42 rows, 7 CORRECT and 6 sentences, with CI [0.375, 0.500] and testable = False. The artifact's own note is that such cells cannot be read. 'DT stratum is a bright spot' omits that consensus ties the local 8B judge there, is below flash-lite on the 63 rows where flash-lite exists, and adds nothing over S4. Symmetrically, the exploratory E2-B '+0.208' is repeated in 'What we have learned' without its decoupled lead [−0.024, 0.314].",
 "suggested_action": "Tag each iteration-5 cell in the summary with n (ERR/COR/sentences) and testable flag, and give the paired comparisons the artifacts computed next to each AUROC. Drop 'collapses' and 'bright spot' in favour of the numbers."}
],
"results_reported": True,
"coverage": "partial",
"blocking": True,
"score": 3,
"confidence": 4
}
open(str(__import__("pathlib").Path(__file__).resolve().parents[3] / "round-5/review/.terminal_claude_agent_struct_out.json"),"w").write(json.dumps(review, indent=1, ensure_ascii=False))
print("ok", len(review["critiques"]))
