import json
W=str(__import__("pathlib").Path(__file__).resolve().parents[3] / "round-4/review/")
crit=[]
def C(cat,sev,d,a): crit.append({"category":cat,"severity":sev,"description":d,"suggested_action":a})

C("evidence","major",
"Most of the previous round's BLOCKING MUST-FIX items are still unaddressed, even though the corrected material now exists on disk twice. (1) The iter-3 hypothesis update (iter_3/upd_hypo/.terminal_claude_agent_struct_out.json §0 'CORRECTED RECORD OF ITERATION 3') restates every iter-3 number with its source and tells the paper step to transcribe it. (2) gen_art_evaluation_3 (art_BvAL_KZTZuw8) Part 4 writes the correction tables: tables/hypothesis_verdicts_iter3.csv (T1(c) 'SIG PASS / FREE NOT_TESTABLE, so NOT CONFIRMED'; T1(e) rename invariance FAILED; M3 INCONCLUSIVE, since the specifications conflict; NET degrades; typing negative), perturb_corrected.csv, rename_selection_dead_end.csv, t2_record.csv, cost_units.csv, coverage_vs_request_iter3.csv, function_inventory.csv, label_facts.csv, corrections_iter12.csv, artifact_id_map.csv and prior_art.csv. The report used only the C8 cost correction and the per-sentence k-costs (§4.6). Still wrong or missing: §3.4 still calls MEANING_RENAME 'the false-alarm diagnostic … meaning-preserving' and still ranks operators by consensus AUROC, and T3 still claims 'polarity-symmetric'. §3.3 and §3.6 item 3 still record T2 as CONFIRMED. §3.5 still redefines M1/M2 (M1 'not formally tested'; M2 as the e/d bookkeeping identity) and still gives the M4 cost column as $0.000024–0.000170 'per sentence', which contradicts §4.6's own $0.000315–0.002206 per sentence. §3.2–3.6 still cite placeholder IDs [ARTIFACT:art_T1_API_bar], art_R_COMP, art_PERTURB_scoring and art_evaluation_2 (the real IDs are in artifact_id_map.csv). E is still called 'held-out' in the iter-3 text and in 'What we have learned'. There is still no section and no marker for the research artifact art_VIF75I5R6f0v. The iter-1/iter-2 correction items (1)–(9) are still unapplied, e.g. §1.4/§1.5 frontier '+0.024 … adds nothing' vs C4, §2.5 item 5 'reversing', '588 common items', 'fitted under solver labels'. §3.1 still has no reasoning block. There is no coverage table, no function inventory, no Part C typing table and no rename-selection dead end. §3.6 still says iter-3 spend was '$1.58 plus T1', but §4.6 says $4.33. 'What we have learned' still leads with 0.954 on R_COMP and '96% of the frontier judge' with no caveat.",
"Apply eval-3 Part 4 in place. For each item, add a '[Correction, iter 4: …; source <path>]' marker next to the struck original text: §3.4 from perturb_corrected.csv (MEANING_RENAME relabelled as an ERROR operator; consensus per-operator AUROC stated to equal a base-endorsement rate; judge cells from perturb_sensitivity.csv; p_peer_text/p_text/l3/S4_local rows; T11 coverage 3,419/5,402). §3.3 from t2_record.csv (T2 NOT CONFIRMED; SIG = the controlled-vocabulary regime; Δ vs the original judge +0.278; frontier subsample; deviations). §3.5 from the evaluation_2 README with the pre-registered M1/M2/M3-local/M4 definitions, the NET +0.356 and cost_units.csv. Replace the placeholder IDs from artifact_id_map.csv. Transcribe hypothesis_verdicts_iter3.csv as '3.7 Hypothesis verdicts', and add coverage_vs_request_iter3.csv and function_inventory.csv. This is transcription only; no new computation is needed.")

C("rigor","major",
"§4.2 (exp 9, art_D7k2ZWgE3nVd) has numbers that do not match the artifact, and gates that are misdefined. I recomputed from results/per_item_csc_E.jsonl (audit/recompute_csc.py/.json). The points reproduce: n 354/196, c_csc strat 0.6136, FREE_exact 0.7697, c_score_align 0.774, e 0.459/0.173, d 0.139/0.323. My sentence-cluster CI for c_csc is [0.501, 0.728], which matches tables.md T4 [0.493, 0.736]. MISMATCHES: (a) every CI in the headline AUROC table is narrower than the source. c_csc: report [0.545, 0.679] vs file [0.493, 0.736]; p_peer_text [0.742, 0.848] vs [0.700, 0.880]; c_score_align [0.711, 0.827] vs [0.682, 0.857]; FREE_exact [0.704, 0.827] vs [0.686, 0.844]; S4_full [0.672, 0.791] vs [0.635, 0.826]; flash-lite [0.592, 0.731] vs [0.568, 0.750]. (b) 'Anchoring by error class' COMPOUND e_CSC 0.643 / e_FREE_exact 0.246. T9 gives 0.282 [0.182, 0.382] / 0.107; 0.643 is the pooled CSC_graded e. With the correct value, COMPOUND is among the LEAST anchored classes, which undercuts the report's reading. (c) The M3 interaction −0.232 [−0.417, −0.041]. T13 gives [−0.770, −0.023], and the stacked-GEE spec −0.351 [−0.694, −0.009] is omitted. (d) The gates are misdefined. prereg_csc_E.json has G2 = 'strat AUROC(CSC) ≥ c_score_align − 0.01 AND pooled AUROC(CSC) > c_score_align on L25'; the report writes it as 'strat AUROC ≥ 0.700'. csc_gate_E.json marks G2 R_AB-part FAIL and L25 NOT_READ, so the overall verdict is NOT_READ, not a plain FAIL. G3-E is the RENAME_SYN false-alarm gate (NOT_RUN); the report calls it 'E2 confirmation'. (e) The 'NET summary' says CSC 'degrades … relative to the FREE baseline'. NET is the within-arm change from word tercile T1 to T3 (T3b); the FREE arms degrade too (FULL FREE_exact +0.452, FREE_align +0.401). (f) 'CSC is below … the flash-lite judge (0.664)' is not significant: the paired Δ is −0.050 [−0.212, +0.107] (T5), and CSC vs S4_full is −0.123 [−0.269, +0.010].",
"Re-transcribe §4.2 from exp 9 tables.md T0–T17 and csc_gate_E.json, with CIs copied verbatim. Fix COMPOUND to 0.282/0.107 and add the full T9 and T9b tables. Replace the gate descriptions with the prereg text and G2 = NOT_READ (R_AB part FAIL). Give M3 under both specifications. Reword NET as length degradation within each arm. State that CSC vs flash-lite and vs S4_full are n.s. on PRIMARY.")

C("methodology","major",
"§4.2 leaves out the facts needed to judge the CSC negative result, and its framing overstates the anchoring mechanism. (1) PRIMARY is a completion-selected subset, not a random one. CTRL makes up 44.9% of its CORRECT rows vs 27.4% on FULL (recomputed), and no stratum reaches 50/50, so L25, the user's priority stratum, is NOT_READ. c_csc is almost binary (tie rate 0.986). The prereg calls the gate PROVISIONAL; the report calls CSC 'a dead end'. (2) The MEANING_RENAME contrast '0.821 vs 0.036' is taken against FREE_exact. Against FREE_ALIGN, the aligner that c_score_align itself uses, e is already 0.750, and Δ CSC − FREE_ALIGN is +0.071 [−0.083, +0.269] (NOT_READ). So aligner-based consensus endorses these errors almost as often as CSC does. On FULL, FREE_ALIGN e on MEANING_RENAME-type errors is 0.624 (T9b). (3) Omitted results: the HYB_MEAN arm (strat 0.709, fails G1); T8, where only 20.2% of CORRECT rows flagged by free-exact have every disagreement vocabulary-resolvable and 53% of disagreements are structural; T10 typing (own_majority 0.185, below the majority class 0.262); T14 system-level τ (CSC 0.256, p = 0.25); T17 phi-4 exemplar leakage (58 CSC calls copied the few-shot exemplar; the clean c_csc is 0.639, and Δ vs FREE_exact clean is −0.132 [−0.251, −0.023]); T15, the 9-peer c_score_align rename ΔFA +0.273 [+0.164, +0.384] under WordNet synonyms; the T2 FULL e/d (FREE_exact d 0.583); the deviations; and G5, whose deduped cost is $2.76e-4.",
"Add a 'Population and selection' paragraph (T0, T0b, tie rate, PROVISIONAL status). Replace the anchoring sentence with the FREE_exact and FREE_ALIGN columns side by side. Add T8, T10, T14, T15 and T17 as tables with their source paths, plus the HYB_MEAN row. Downgrade 'dead end' to 'provisional negative on a completion-selected subset; L25 and RENAME untested'.")

C("evidence","major",
"§4.3 (exp 10, art_pAmLrGqsmFUx) draws a conclusion its own tables contradict. 'FREE consensus achieves near-perfect recall on PERTURB (e ≈ 0, recall ≈ 1.0)' leaves out the matching false-alarm rate on the verified-CORRECT bases (T4). I recomputed from results/perturb_csc_scores.jsonl (audit/recompute_perturb_csc.json). Base FA at c > 0.5 is 0.712 for c_align_exp8 on E, 0.803 for FREE3_exact on E, 0.986 for FREE3_exact on R_COMP and 0.757 for FREE3_align on R_COMP, with mutant recall 0.998–1.000 in every case. A score that flags 71–99% of verified-correct formulas has trivial recall. The same problem affects 'All consensus variants flag RENAME controls at 85–100% FA': the paired flip rates are 0.18–0.53 (c_align E SYN 0.182, NONCE 0.327). The report omits them, so most of that FA is base FA. Other misreadings: (a) LOCAL2 e 0.341 is read as 'weaker models failing to distinguish mutants'. Every one of those endorsements is an insufficient-peer tie at c = 0.5 (share exactly 0.5 = 0.341, recomputed; T3 e_excl_insufficient 0.012/0.007). (b) The judge's 12.4% mutant miss rate is said to be 'matching the iteration-3 E endorsement rate', but that 0.124 is END_MAJ e on real errors, a different quantity. (c) Typing: 'oracle' repairs against the known gold base, so it is not a gold-free metric. free3 on E is 0.123 [0.081, 0.169]; the report gives the pooled 0.085, which includes R_COMP rows at 0.0. (d) The controls table mixes sources: FREE3_exact REORDER/CONTRA 0.986 is R_COMP, while the E values are 0.842/0.840. (e) T4 (d rises with length: c_align 0.47/0.80/0.91 by tercile) and T8 (R_COMP FREE label-free agreement, ALIGN 0.219) are omitted.",
"Add T4 (d on bases) next to every recall figure and state plainly that FREE consensus recall ≈ 1 comes with base FA 0.71–0.99. Add the paired base FA and flip columns from T5. Correct the LOCAL2, judge-12.4% and typing sentences as above, and label the oracle as gold-using. Split the controls table by base_source.")

C("rigor","major",
"§4.6 and 'What we have learned' misread eval 3 (art_BvAL_KZTZuw8). (1) 'The predicted d_floor (0.402) closely matches the observed END_MAJ d (0.415), indicating that the Part-1 model accounts for the observed disagreement.' The artifact says the reverse. The instrument bracket is [0.396, 0.415], the pre-registered gap_closed rule is ill-conditioned (denominator 0.013), and the instruments 'cannot see most vocabulary divergence'. (2) 'R_exact AUROC (0.683) is the theoretical performance of cross-family exact-match consensus on R_COMP under independent vocabulary.' 0.683 is d under the exact rule on E's 3-pool (tables/p1_rule_cuts.csv); it is not an AUROC and not R_COMP. 'What we have learned' then repeats 'R_COMP FREE d_floor 0.402, theoretical AUROC 0.683'. Both numbers are E quantities, and neither is an AUROC. (3) The calibration failure is attributed to 'vocabulary-driven non-transitivity'. The artifact says predicted FREE endorsement 0.20 vs actual SIG 0.575, i.e. the instruments under-count vocabulary effects, and D7 notes that SIG changes granularity and structure as well, so the SIG−FREE drop is an upper bound. Non-transitivity (0.131) is a separate diagnostic. (4) Omitted: 77% (9-family) and 61% (3-pool) of the non-agreeing peers of CORRECT candidates are labelled ERROR, so d is mostly peer error, not vocabulary; pair classes (IRREDUCIBLE 69.4%); the specificity placebo (VOCAB agreements are not label-specific); c_vres L25 −0.014 [−0.028, −0.001]; NET DEGRADES under every rule (+0.35 to +0.39); the no-anchoring oracle floor 0.385 and L25 0.542 vs 0.735; SIG row endorsement 0.575 vs FREE 0.193; the p3 power grid (L25 250–400 → MDE 0.130–0.103, all MARGINAL); R_COMP FREE needs ≥ 200 CORRECT rows; deviations D1–D10; the reusable functions table.",
"Rewrite §4.6 from the eval-3 README 'Results in one table' and 'What this means' sections, row for row with source paths. Delete 'closely matches … accounts for' and the '0.683 theoretical AUROC on R_COMP' wording in both §4.6 and 'What we have learned', and replace them with 'the post-hoc instruments predict almost no fix and are shown to under-count vocabulary effects (calibration error −0.372)'. Add the 77%/61% peer-labelled-ERROR decomposition as the main mechanism finding.")

C("evidence","major",
"§4.4 and §4.5 (datasets 4 and 5) drop caveats that change how the data should be read, and §3.3 now has results computed on labels this iteration invalidated. E2 (art_2OmxzMInZZJY): the report says the gate balanced accuracies 'all pass'. panel_drift_E2.json says the stop rule is 'UNDECIDED', with passes = false and combined majority agreement 0.394 over all items. On the 22 replayed unambiguous track-H judgements, today's panel flags only 0.12 of original errors vs 0.84 in E (orig_flagged_rate_unamb). That is a drift warning, small n, and it is not recorded. Deviations D0–D7 (including D1, ProverQA gold under the MALLS audit shim, and D4, re-issued phi-4 calls) are not listed. The label recount I did matches: 36 ERROR / 274 UNRESOLVED / 20 UNPARSEABLE / 0 CORRECT. R_COMP FREE (art_Ia_FT284H33j): the counts reproduce (759/1,506/188/199). But '70.7% contaminated' treats MAPPED as CORRECT, while the artifact calls MAPPED an upper bound (executor audit: 0.867 faithful). The disagreement sample includes a MAPPED certificate that swaps LivesIn and StudentInClass, i.e. a real error passing the search. Also omitted: old/new kappa 0.058; rescue rate by template (T8 0.27, T9 0.37–0.43); deviations D1–D9, including D6, which amends the map family after the freeze. Most importantly, §3.3's FREE numbers (c_align − judge +0.214; 'falls to ~0.80') were computed on the iter-3 FREE tier-A labels that this artifact shows to be mostly wrong, and §3.3 carries no in-place correction.",
"Add the drift stop-rule status and the 0.12-vs-0.84 track-H signal to §4.4, with the deviations list. Word §4.5 as 'up to 70.7% (MAPPED is an upper bound; 13% of MAPPED unfaithful in audit)', and add kappa, rescue-by-template and the deviations. Insert '[Correction, iter 4: FREE tier-A labels shown to over-call ERROR (297/420 MAPPED); the FREE deltas in this section are void; source gen_art_dataset_5/results/old_label_agreement.json]' into §3.3.")

C("scope","major",
"Iteration 4 spent its budget on a new metric variant (CSC) and a CPU-side mechanism analysis over a panel its own power analysis calls underpowered. It did not spend it on the graded samples that would decide the question. eval-3 power_E2.json: L25 yield 0.37; detecting the observed +0.069 needs ~882 planned L25 sentences; E2's 350 give MDE80 0.112 and power 0.32–0.47. R_COMP FREE needs ≥ 200 CORRECT rows. Against the user's request, the new section adds no testable result on long, heavily conditioned sentences: CSC L25 is NOT_READ, E2 has 0 CORRECT rows, and R_COMP FREE has an empty CORRECT class. The operating condition 'no ontology or controlled vocabulary' is still unvalidated: the only positive new numbers (SIGPROXY 0.930; d 0.149) come from the signature-given regime the user put out of scope. 'Which kind of error' is again negative outside shared vocabulary (free3 typing 0.123 on E, ≈ the judge). The report does not state any of these as answers to the request, and 'What remains' ranks completing E2 and the gloss together with more CSC arms.",
"Add the 'Coverage against the request' table (start from coverage_vs_request_iter3.csv and update it with iter-4 rows), with explicit one-line answers: long sentences → untested in iter 4; no-controlled-vocabulary → consensus unvalidated (FREE untestable); error type → negative. In 'What remains', rank first the R_COMP FREE gloss (~$1.8, gives CORRECT labels in the in-scope condition) and E2 completion sized to ≥ 237 usable long-pool sentences with the long pool pre-declared primary. Drop the remaining CSC PERTURB arms until those have run.")

C("clarity","major",
"§4.1 records what iteration 4 did but not why. It omits: the previous review (score 3, blocking, 12 items) and which of those objections iteration 4 set out to answer (eval-3 Part 4 was built for this, and the report does not say so); the iter-3 upd_hypo decision (move = DEEPEN; title 'Peer agreement in the candidate's own words'; the §0 corrected record); the prediction CSC was meant to test (a lower d without a higher e, with eval 3's pre-registered d_floor prediction as the yardstick) and the stopping rule; the five planned artifacts with their planned vs actual spend. The budget event is described three different ways ('budget event at $0.108', 'run-wide budget ($7.00) exhausted by earlier artifacts', 'exhausted at 07:26 UTC') and never reconciled into a spend table. Summing the ledgers gives exp 9 $0.108, exp 10 $0.0000088, dataset 4 $0.241, dataset 5 $0 and eval 3 $0, about $0.35 in total. That leaves most of the $7 'Test idea' budget spent by something the report never names.",
"Open §4 with an 8–10 line reasoning block drawn from iter_3/upd_hypo and iter_4/gen_strat/gen_strat_1: the previous review score and blocking status, the move, the CSC prediction and gate definitions, the artifacts planned. Add an iter-4 spend table from each artifact's cost ledger, and say which process consumed the run budget before 07:26.")

C("novelty","major",
"The iteration's positive claims have no nearest-neighbour check, and the research artifact still has no section. The claims are 'Vocabulary sharing reduces d by 0.61–0.84 while maintaining perfect mutant recall' and 'Error typing requires shared vocabulary'. Supplying a predicate list is a documented lever for NL→FOL: Vossel et al. 2025 (arXiv 2509.22338, cited as [24]) report that 'predicate availability boosts performance by 15–20%'. ARc (2511.09008, [19]) scores translations over a fixed shared schema precisely so that k translations can be compared. What SIGPROXY adds is a measured d reduction on long templated sentences in an out-of-scope controlled-vocabulary regime, and the record should say only that. The anchoring finding (peers given the candidate's symbols copy its errors) is the correlated-failure mode the report itself cites from Chen & Avizienis [25]. Its new element is the per-class e measurement, but the MEANING_RENAME contrast shrinks to +0.071 n.s. against the aligner baseline. art_VIF75I5R6f0v still has no [ARTIFACT] marker, no scoop-rule statement and no C1–C5 verdict table, although eval 3 exports prior_art.csv for exactly this.",
"Add '3.x Prior-art positioning [ARTIFACT:art_VIF75I5R6f0v]' (scoop rule, closest-neighbour table, C1–C5 verdicts with qualifiers, from prior_art.csv). Under §4.3's shared-vocabulary claim and §4.2's anchoring claim, add one sentence each naming Vossel/ARc and Chen & Avizienis, and saying what the measurement adds.")

C("evidence","minor",
"The 'Dead ends accumulated' table is incomplete, and one of its rows gives the wrong reason. Missing: the iter-3 pre-registered rename-invariant selection (HYB/NF-anchored both INELIGIBLE, rename_selection_dead_end.csv); Candidate B1 (planned, never ran; gen_art_experiment_2 empty); the FOL-Triage fused rewrite-FA gate failure; P2/P4 REFUTED; CSC_graded, CSC_multi and HYB_MEAN (all fail G1); the E2 EXC-core stratum (supply exhausted, D3). The c_nf row cites 'SWAP recall 0.512', but the evidence that actually ended it is the pre-registered selection failure (PERTURB RENAME_SYN/NONCE FA 0.686/0.485 at screen thresholds) together with its blindness to MEANING_RENAME (within-base AUROC 0.499 on a real error class).",
"Extend the table with these rows, each with its source file, and correct the c_nf reason.")

C("rigor","minor",
"The cost statements still disagree across sections. §3.5 gives $0.000073/sentence for k = 3 and calls consensus cost 'negligible' next to the judge's $0.000049/call, while §4.6 gives $0.000946/sentence. §3.3 gives 'frontier 6.07×' per candidate, while §3.2 gives 30.2× per item. §3.6 gives iter-3 spend as '$1.58 plus T1', while §4.6 gives $4.33. 'What we have learned' says '3 peer families suffice for 97%' without the long-sentence k95 = 5.",
"Transcribe cost_units.csv as one cost table with units (per item / sentence / candidate; FULL vs MARGINAL). Correct §3.5 and §3.6 in place, and add the tercile k95 to the summary.")

review={
"overall_assessment":
"Iteration 4 adds five executed artifacts, and all five are present in the report: CSC on E (exp 9), CSC/PERTURB zero-cost arms (exp 10), the E2 partial dataset, the R_COMP FREE name-free labels, and the T8 vocabulary evaluation. Dead ends from budget stops are labelled as NOT_RUN/UNTESTED rather than hidden, which is good. The point estimates I recomputed from raw files reproduce. From exp 9's per_item_csc_E.jsonl: c_csc strat AUROC 0.614, FREE_exact 0.770, c_score_align 0.774, e 0.459/0.173, d 0.139/0.323. From exp 10's perturb_csc_scores.jsonl: base FA and mutant recall. From dataset 4: the E2 label counts (0 CORRECT). From dataset 5: the FREE label counts. The record still fails as a record, in three ways. (1) The previous round's blocking MUST-FIX items remain almost entirely unaddressed. This happened even though the iter-3 hypothesis update and eval-3 Part 4 wrote the corrected verdicts, tables and artifact-ID map to disk for exactly this purpose. T2 is still CONFIRMED against its own criterion, MEANING_RENAME is still read backwards, M1/M2 are still redefined, the M4 cost column is still 13× too low, placeholder artifact IDs remain, and E is still 'held-out'. (2) The new iteration-4 section has transcription errors and misreadings of its own. The CIs in the CSC headline table do not match the source. The COMPOUND anchoring values are wrong (0.643/0.246 vs 0.282/0.107). The gates are misdefined (G2 described as '≥ 0.700'; G3-E described as 'E2 confirmation'). 'FREE consensus has near-perfect recall' is written without the 0.71–0.99 false-alarm rate on verified-correct bases. LOCAL2 endorsement is actually insufficient-peer ties. And eval 3's result is inverted: the report says 'the d_floor model closely matches, accounting for disagreement' where the artifact says the instruments under-count and the rule is ill-conditioned, and it presents E's 3-pool exact-rule d = 0.683 as a 'theoretical AUROC on R_COMP FREE'. (3) Coverage of the request did not move. Nothing new is testable on long sentences or in the no-controlled-vocabulary condition, and the power analysis shows the planned confirmation set is underpowered. Because conclusions in §3.3, §3.4, §4.3 and §4.6 contradict the run's own tables, soundness is 1 and the review is blocking. results_reported is true: the headline points come from executed artifacts and I recomputed them. The CIs in §4.2 are unverified, and I could not reproduce them.",
"strengths":[
"Every iteration-4 artifact appears in the report with an [ARTIFACT] marker, and budget-stopped arms are labelled UNTESTED/NOT_RUN/NOT_TESTABLE rather than silently dropped.",
"The CSC negative result is reported as a negative result, with its mechanism (e rises while d falls). I recomputed the core point estimates (0.614, 0.770, 0.774; e 0.459 vs 0.173; d 0.139 vs 0.323) from the per-item file.",
"The R_COMP FREE name-free labeller is described with its soundness replay (0/1,595 false errors) and its executor audit, and the report explicitly says iter-3 FREE labels over-call ERROR.",
"Correction C8 is applied in place with a marker, and §4.6 gives the correct per-sentence k-pool costs.",
"The E2 status is recorded honestly as NOT testable, with the EXC-core deviation D3 and the MDE80 of 0.112."],
"dimension_scores":[
{"dimension":"soundness","score":1,"justification":"Several conclusions contradict the run's own files: T2 CONFIRMED against the §3.1 criterion; MEANING_RENAME read as meaning-preserving; 'FREE consensus near-perfect recall' with base FA 0.71–0.99; eval-3 'model accounts for disagreement' when the artifact says the reverse; 0.683 d reported as an AUROC; COMPOUND anchoring values and CSC CIs mismatched to the source; gates misdefined.","improvements":["Re-transcribe §4.2 and §4.3 from tables.md with verbatim CIs and base-FA columns (raises soundness to 2).","Apply eval-3 Part 4 corrections in place for §3.3–3.6 (needed to reach 3)."]},
{"dimension":"presentation","score":2,"justification":"The iteration is well organised and plainly written, but it carries no reasoning block. Corrected and uncorrected numbers sit side by side (cost, frontier), and placeholder IDs remain.","improvements":["Add §4.1 reasoning and a spend table.","Replace the placeholder IDs from artifact_id_map.csv."]},
{"dimension":"contribution","score":2,"justification":"All artifacts are mentioned, but most of their tables are left out: exp 9 T8/T10/T14/T15/T17 and the HYB arm; exp 10 T4 d-on-bases, flips and T8; eval 3 Part 1 decomposition, power grid and Part 4; the dataset deviations. Earlier gaps (research artifact, exp 8 Part A/C, eval-2 verdicts) persist.","improvements":["Transcribe the omitted tables with their source paths.","Add the research-artifact section and the dead-end rows."]}],
"critiques":crit,
"results_reported":True,
"coverage":"partial",
"blocking":True,
"score":3,
"confidence":4}
json.dump(review,open(W+".terminal_claude_agent_struct_out.json","w"),indent=1,ensure_ascii=False)
print(len(crit))
